name: "Build git-commit-generator"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Flake check
        run: nix flake check --all-systems
      - name: Build Git Commit Generator
        run: nix build '.#git-commit-generator'
